_target_: configs.cfg_mappings.Configs
_recursive_: false

api_key: api-key
base_url: base-url

embed_name: embedding-name
extract_model_name: qwen-long
model_name: model-name

extractor:
  _target_: cfg_mappings.ExtractorConfigs
  model_name: ${extract_model_name}
  temperature: 0.2
  prompt_file: prompts/pdf_extract_prompt.md
  num_pdf_concurrent: 5